kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    {{ if eq .Values.service.type "LoadBalancer" }}service.beta.kubernetes.io/external-traffic: "OnlyLocal"{{ end }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    release: "{{ .Release.Name }}"
  ports:
    - name: api
      port: 3000
  type: {{ default "ClusterIP" .Values.service.type }}